### ISSUE TITLE
[ENHANCEMENT] Algorithms in Go Lang - folder structure

### ISSUE THREAD

**Issue by KamalDGRT** [HarshCasper/NeoAlgo#11]
Implementing the algorithms in Go Language would be a plus.

**Comment by mar-galho** [comment]
Hi @KamalDGRT ! 

The algorithms can be implemented by anyone who has knowledge in the language :)

I have unassigned us in this post, so that any collaborator who desires to fork the repo, create the folder and implement the algorithms can do it.

I appreciate the great suggestion!

**Comment by KamalDGRT** [comment]
Thank you @ricardoprins

**Comment by Sanketwable** [comment]
I want to work on this

**Comment by KamalDGRT** [comment]
Me too.
And I think it is best to store the code for each algorithm of go language in a separate folder. 
This is because, when 2 .go files are in the same folder, the execution of the same will result in error.

**Comment by Sanketwable** [comment]
That's a good idea.  I was thinking of generating different packages for each algo. And can be accessed by the single main package. So there will be no error generated and everyone will be able to access the packages by importing github.com/TesseractCoding/NeoAlgo/"Folder-Name".

**Comment by mar-galho** [comment]
Makes sense to me!

**Comment by Sanketwable** [comment]
Please assign this issue so that I can start contributing.

**Comment by mar-galho** [comment]
awesome! let's do it!

**Comment by mar-galho** [comment]
Alright, before we go ahead, we need to discuss a few things.

If we add a "one-folder-per-code" model, we'd end up with a reasonably complex structure...
However, if we keep just the "one folder per topic" model, we'll need that every person looking for code understands that they'd be browsing the repo for code only, and that they'll need to place the code within the proper structure in their own execution environment...

Which of the two models will we choose?

Since I'm at this moment running a bot to create a basic folder structure for the whole repository, I'll be sticking temporarily to the second model until we make a decision here.

I am also renaming the issue to make the topic clearer.

**Comment by Sanketwable** [comment]
"one-folder-per-topic" will be preferred by me because it will also help users import packages. As I mentioned before.
https://github.com/TesseractCoding/NeoAlgo/issues/11#issuecomment-650795225 

I also prefer the second model.

**Comment by mar-galho** [comment]
I believe this is outdated. Closing now.
