### ISSUE TITLE
Add Pre-Order Tree Traversal

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/NeoAlgo#124]
**Algorithm:** 

[Pre-Order Tree Traversal](https://en.wikipedia.org/wiki/Tree_traversal)

**DS:** 

Trees

**Languages Supported:**

- C
- C++ [ Assigned to @chaitanya003 ]
- C#
- Java [ Assigned to @chaitanya003 ]
- Javascript
- Python

**Comment by chaitanya003** [comment]
Could I do this in C++ and Java ?

**Comment by HarshCasper** [comment]
I have assigned you the Issue @chaitanya003 

Please follow the general guidelines:

- Make a Branch off your Master and work on that.
- Make a proper README of how your Script works and what all libraries and modules you have used.
- Add Proper Comments and focus on Clean Code, in practice.
- Also reference this Issue in your PR so that it becomes easy for us to review.

**Comment by GSNCodes** [comment]
Ready to implement this in Python!
@HarshCasper

**Comment by bagladivyang03** [comment]
Can i do In C can u pls assign me this

**Comment by Yash-Thakare22** [comment]
I would like to work on this issue in C

**Comment by pradeep98** [comment]
@HarshCasper I would like to implement it in PYTHON. I will be implementing it using both recursion and Iterative. Why iterative?  Because in recursive function has to add to the stack with each recursive call and keep the values there until the call is finished, the memory allocation is greater than that of an iterative function. This makes the implementation to exceed memory limit and at points time limit as well for high depth trees. Recursive approach makes the problem easy however, implementation using iterative makes it medium to hard problem. Looking forward for your reply.
