### ISSUE TITLE
Dynamic programming algorithms in python

### ISSUE THREAD

**Issue by kartikp36** [HarshCasper/NeoAlgo#1440]
### Winter of Code
Add the following  dynamic programming algorithms in Python:

1. Edit Distance
2. Knapsack-Unbounded
3. Knapsack-0-1
   

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes.

## Motivation
Of all the algorithms, dynamic programming algorithms were difficult ones to understand for me. So to try sharing the knowledge.

## Pitch
Widely used method for solving optimization problems by solving the smaller subproblems. And I found that  I could add this to [Python/dp](https://github.com/TesseractCoding/NeoAlgo/tree/master/Python/dp) as it has only one problem yet.(ie. CoinChange)

**Comment by HarshCasper** [comment]
Hello @kartikp36 

Thanks for making the Issue! 

As a rule of the thumb, every Issue and a corresponding PR should be as atomic as possible. This simply means that it should be an addition or updation of only one thing logical. This makes the review part easy and flexible. 

I will make an exception here because its a part of your proposal. However, I will request you to make three different PRs for the same issue. Please have three branches where you can push your changes and make a corresponding PR because we don't want a single PR to be overlapped with a lot of code. 

If you have any further doubts, let me know right here or on the Slack Workspace. You have 7 Days to resolve this Issue!

**Comment by kartikp36** [comment]
Thank you for assigning me ! @HarshCasper 
Noted, I'll have three different branches.

> Hello @kartikp36
> 
> Thanks for making the Issue!
> 
> As a rule of the thumb, every Issue and a corresponding PR should be as atomic as possible. This simply means that it should be an addition or updation of only one thing logical. This makes the review part easy and flexible.
> 
> I will make an exception here because its a part of your proposal. However, I will request you to make three different PRs for the same issue. Please have three branches where you can push your changes and make a corresponding PR because we don't want a single PR to be overlapped with a lot of code.
> 
> If you have any further doubts, let me know right here or on the Slack Workspace. You have 7 Days to resolve this Issue!
