### ISSUE TITLE
Addition of code linters

### ISSUE THREAD

**Issue by shubhank-saxena** [HarshCasper/NeoAlgo#1460]
## 🚀 Feature

Addition of various code linters which will help to maintain code quality. 

## Motivation

The repository houses algorithms from various languages. It will be a good practice if we had linters for every language so that we are able to maintain the code consistency. 

## Pitch

This feature can be used as a pre-commit check as well as a travis test so that the integrity of the code is maintained!

**Comment by Neelaksh-Singh** [comment]
Hi can we add super-linter to this issue.
https://github.com/github/super-linter

**Comment by shubhank-saxena** [comment]
> Hi can we add super-linter to this issue.
> https://github.com/github/super-linter

Hello @Neelaksh-Singh . I am not sure about the rules and the flexibility we can get from this. Can you show an example of this in application?

**Comment by Neelaksh-Singh** [comment]
Sure 
https://user-images.githubusercontent.com/15258962/85165778-2d2ce700-b21b-11ea-803e-3f6709d8e609.gif

We can also create our custom rules to the above.

Speaking of limitations -  
1. Due to being completely packaged at run time, you will not be able to update dependencies or change versions of the 
   enclosed linters and binaries
2. Additional details from package.json are not read by the GitHub Super-Linter
3. Downloading additional codebases as dependencies from private repositories will fail due to lack of permissions

**Comment by shubhank-saxena** [comment]
@Neelaksh-Singh this sounds good! I don't think there is a high need to change to linter versions that frequently. 
As far as part 3 is considered, we can make sure that all the linters that we use have their dependencies in the public domain!

You can start working on this, and please feel free to ask any doubts if you are stuck with anything!

Also, I would suggest splitting the linters in independent PRs. Like Python can have it's own PR, C/C++ other and so on. Also, make sure that we have a discussion of the linter that we are going to use!

**Comment by Neelaksh-Singh** [comment]
Hi I have created the YAML file for the Linter.
It'll validate new files that are being pushed to the master branch and mark the status of each individual linter run in the Checks section of a pull request.

I haven't configured it for specific Language though, since it'll fail due to it's nature. 
The elaborate list for linter's being used can be found here :-  https://github.com/github/super-linter

If everything is to your satisfaction then we may proceed ahead.
https://drive.google.com/file/d/10NZhrIcc6YlNS3bfUbdW9X7kb1pw8KNW/view?usp=sharing

**Comment by shubhank-saxena** [comment]
This looks good to me. You can start with a PR and then we can work around with selecting specific linters from the options and have them in yaml file. We can't have all of them as it will create a lot of linting issues. Plus, for every linter running, we will have to have some specified rules

**Comment by Neelaksh-Singh** [comment]
Hi I have done a merge on my forked repo. If it isn't showing then can you add the file in the below link into your workspace directory.
https://drive.google.com/file/d/10NZhrIcc6YlNS3bfUbdW9X7kb1pw8KNW/view?usp=sharing

**Comment by shubhank-saxena** [comment]
Hello @Neelaksh-Singh this looks good! Now we have next step - Figure out how to implement just specific file lint checks.
Also, I would suggest that you use github gist or pastebin instead of Google Drive to host a code snippet
