### ISSUE TITLE
Ways to reach the n'th stair  / Winter Of Code

### ISSUE THREAD

**Issue by ghost** [HarshCasper/NeoAlgo#1526]
## 🚀 Feature

(A clear and concise description of what the feature is.)
A program to count the total number of ways in which a person can reach to the top.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

(Please outline the motivation for the proposal.)
A classic interview question based on Dynamic Programing.
Winter of Code

## Pitch

(Please explain why this feature should be implemented and how it would be used.)
It is a very important question which tests one's knowledge in dp and problem solving.

**Comment by ghost** [comment]
@iamrajiv  Please assign this issue to me in C++.

**Comment by YASH01009** [comment]
@shraddhavp Please assign me this in Java

**Comment by Neilblaze** [comment]
@YASH01009 Go for it!

**Comment by aeyshubh** [comment]
This issue is already assigned to me in issue #1455 in Java and i have created a PR too #1584  please resolve this issue @Neilblaze .And i am also assigned to do this in Python.
Regards,
Shubham Patel

**Comment by YASH01009** [comment]
@ShubhamPatel33 If I am not wrong, we missed out on an issue, in issue #1455 the relative order does not matter, means 1 2 and 2 1 are the same, as that was mentioned in the issue. But this issue counts them different. In issue #1455 we count #combinations and here we count #permutations.

**Comment by aeyshubh** [comment]
Yash in ,my code 1,2 and 2,1 are different

**Comment by Neilblaze** [comment]
@YASH01009 @ShubhamPatel33 don't strife between yourselves guys. Since the contribution flow goes via `first claimed first merge` (keeping accuracy in mind), so the PR priority of @ShubhamPatel33 shall be more than @YASH01009.

I wasn't that much aware of the content inside #1584, it's always recommended to create separate PR's than creating one for multiple issues. It becomes a tad difficult for us to evaluate like this.

Since Java implementation was assigned first in [here](https://github.com/TesseractCoding/NeoAlgo/issues/1455#issuecomment-743029558), @ShubhamPatel33 will be the one who's PR shall be checked first. If any sort of discrepancy found, automatically @YASH01009 shall be assigned for it. For now, #1526 shall be locked to CPP implementation of `Ways to reach the n'th stair`.

I'm not unassigning anyone right now. @YASH01009 feel free to grab any other open issue or create a new one.
Apologies for any inconvenience caused.
