### ISSUE TITLE
Heap based problems

### ISSUE THREAD

**Issue by 1711shashank** [HarshCasper/NeoAlgo#1546]
Separate section for Heap based problems in C++.

Have you read the Contributing Guidelines on Pull Requests?
Yes

Motivation
Such problems will help users understand the application of Heap.

Pitch
Only knowing the definition of Heap is not very useful until we have applied it on some problems.

**Comment by 1711shashank** [comment]
@atarax665 

can I work in this?

**Comment by atarax665** [comment]
@1711shashank Make individual issues for various heap related problems so that I can later assign them to other contributors in different languages. I don't think making a separate section for heap is necessary as they have limited direct use. But you can always add heap based problems in ```cp folder``` or some heap based algorithm in ```others folder```.

**Comment by 1711shashank** [comment]
ok 👍👍
