### ISSUE TITLE
[Winter of Code] Roadmap for Data structures and Algorithms 

### ISSUE THREAD

**Issue by joeyouss** [HarshCasper/NeoAlgo#1641]
## 🚀 Feature

As mentioned in my proposal, I would like to create a big of roadmap for helping the beginners with data structures and Algorithms and how they can go about starting with data structures

## Motivation

When I first started out as a beginner it was extremely tough for me to figure out how to go about with DSA. Hence, I think there are many people searching for the same.

## Pitch

When people come to NeoAlgo, they get to see DSA implemented in different languages but they might get confused as to where could they start especially if they're beginners. So this would make NeoAlgo beginner friendly and help them go about understanding the repo more easily.

**Comment by HarshCasper** [comment]
Hello @joeyouss 

Thanks for raising this! You can go ahead with this and make sure that your Roadmap should be in a Markdown Format and pushed to the `resources/` directory, which isn't created yet. Please keep me in a Feedback Loop over Slack so that I can review it right there before you make a PR.

**Comment by joeyouss** [comment]
Thank you! I will do in the same format and submit it
