### ISSUE TITLE
Implement N-Queen Problem in C++ and Java.

### ISSUE THREAD

**Issue by Shreyash41** [HarshCasper/NeoAlgo#2210]
## 🚀 Feature

I would like to contribute to the N-Queen problem In C++ and JAVA. Please assign it to me as a part of GSSOC 2021.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES.

**Comment by ankan1811** [comment]
I would like to do N-Queen problem In C++ . Please assign it to me as a part of GSSOC 2021.

**Comment by HarshCasper** [comment]
@ankan1811 : C++ 
@Shreyash41 : Java

**Comment by ankan1811** [comment]
@HarshCasper @atarax665   Sir Since this is for GSSoC'21 it would be really nice if any mentor could add a GSSOC'21 label for this issue to avoid confusion.

**Comment by ritvij14** [comment]
@HarshCasper @atarax665 I would like to take this issue in Golang and JS.
Also, has GSSOC '21 officially started? I couldn't see any announcements on their discord server.

**Comment by HarshCasper** [comment]
@ritvij14 Since you have been a previous contributor, you might understanding that managing individual contributions through a single issue is often hard. You can create a separate issue for Golang and JS and I will assign you the same.

The Coding Period has started. Contributors have started creating Issues and making PRs from beforehand.

**Comment by ritvij14** [comment]
@HarshCasper alright understood, thanks for the clarification. I will make the separate issues 👍

**Comment by AasthaGoyalgit** [comment]
Hey!!

I am interested in this issue in java  as a GSSOC'21 participant .
I'll be glad to work on this issue.

Thanks!!
