### ISSUE TITLE
Noble Integer in C,C++ and Python

### ISSUE THREAD

**Issue by rohanbabbar04** [HarshCasper/NeoAlgo#2371]
## 🚀 Feature

An integer x is said to be Noble given an array if the number of integers greater than x are equal to x. 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation
To contribute as a part of GSSOC '21

## Pitch

It is a new and interesting integer. So would like to contribute in C,C++ and Python.

**Comment by ankan1811** [comment]
I want to contribute this in C++ as a part of GSSoC'21. Please assign it to me. @bhav09

**Comment by kushal13112001** [comment]
I want to contribute this in Python as a part of GSSoC'21.

**Comment by bhav09** [comment]
@kushal13112001 and @ankan1811 this issue will be assigned to @rohanbabbar04  as he came first. Issues are assigned on a first come first serve basis.

**Comment by ankan1811** [comment]
@bhav09 So he can work in any one language out of those 3 . I can work in C++ . Because different languages will have different PRs... Previously, I was assigned like this here  only... Please look if it is possible. Like this : [ #2158 ](https://github.com/TesseractCoding/NeoAlgo/issues/2158)    
Thanks.
