### ISSUE TITLE
Equal Sum Partition Problem : Dynamic Programming, C++

### ISSUE THREAD

**Issue by nandinit02** [HarshCasper/NeoAlgo#2399]
## 💥 Proposal

I would like to write a code for the Equal Sum Partition Problem, this algorithm will help to determine whether a given set can be partitioned into two subsets of equal sum. I will use C++ with proper comments and explanation of the code.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

@HarshCasper  Please assign me this issue under GSSoC'21.

**Comment by srividhya14** [comment]
I am Gssoc 21 participant . I request you to assign me this issue.

**Comment by somya1252** [comment]
Hello @HarshCasper  as a participant of GSSoC'21 I would like to work on this problem 'Equal Sum Partition Problem' using C++.
💥 Proposal
Given a non empty array we need to find if the array can be partitioned into two subsets such that the sum of elements in both subsets is equal.
Approach - If the sum of the entire array is S then the sum of each of the two subsets should be S/2. If sum S = odd then we can never find 2 subsets having equal sum because all the elements are integer. If sum S = even then we may/may not find 2 subsets having equal sum. If it is possible to form a subset sum = S/2 then the rest of the elements will be of equal sum(i.e. S/2) and hence we can find 2 subsets having equal sum.
Here we have the array as {1,5,11,5}
S = 22
we found a subset {1,5,5} whose sum is equal to S/2, therefore the other subset will be {11} and we will return True.
Hey @HarshCasper please look into this issue and please assign to me.

**Comment by nandinit02** [comment]
@HarshCasper Sir, I request you to please assign me this issue , as you haven't assigned me yet, so that I could start working on it.
