### ISSUE TITLE
Finding Nth term of fibonacci series in optimized way in C++

### ISSUE THREAD

**Issue by chandankrsahu** [HarshCasper/NeoAlgo#507]
## 🚀 Feature

Cpp program for finding Nth term of fibonacci series in optimized way .

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by chandankrsahu** [comment]
I would like to contribute  as a part of HackinCodes. @plazzy99 @Kajol-Kumari @Abhijit2505

**Comment by sukritidawar** [comment]
I want to work on this issue in python, java

**Comment by Kajol-Kumari** [comment]
Hey @chandansahuji I think we already have issues opened for fibonacci [here](https://github.com/TesseractCoding/NeoAlgo/issues/466) and [here](https://github.com/TesseractCoding/NeoAlgo/issues/14). If your issue is different from them, please explain it how, otherwise feel free to close this issue.

**Comment by Jkp2072** [comment]
@Kajol-Kumari  i think this problem isnt there in c++. i would like to solve in c++

**Comment by chandankrsahu** [comment]
Hello @Kajol-Kumari ,the method I am going to implement was using a mathematical formula to derive the nth term of the fibonacci series .[Please visit this link for  mathematical proofs of the same.](http://www.maths.surrey.ac.uk/hosted-sites/R.Knott/Fibonacci/fibFormula.html)
