### ISSUE TITLE
Priority Queue in Python

### ISSUE THREAD

**Issue by noviicee** [HarshCasper/NeoAlgo#6566]
## 💥 Proposal

Implementation of Priority Queue in Python.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by noviicee** [comment]
> /assign

@amulyavarshney
I have already created a PR.
So no need to create another for the same. You can take up another issue.
Thank you

**Comment by amulya-0706** [comment]
@noviicee I think your PR has not been merged to the master branch and it had failed few checks. I would suggest you to confirm this once with the maintainers. Moreover it is about 24 days since you make the PR and the issue was open when I requested to assign it to me.

Please check it and let me know.

**Comment by noviicee** [comment]
> @noviicee I think your PR has not been merged to the master branch and it had failed few checks. I would suggest you to confirm this once with the maintainers. Moreover it is about 24 days since you make the PR and the issue was open when I requested to assign it to me.
> 
> Please check it and let me know.

Yes. I have shared it with the maintainers. They are reviewing the PRs and will review it soon. Thankyou.
